angular.module('goboxWebapp')

.constant('SyncEventKind', {
    FILE_CREATED: 'FILE_CREATED',
    FILE_MODIFIED: 'FILE_MODIFIED',
    FILE_COPIED: 'FILE_COPIED',
    FILE_MOVED: 'FILE_MOVED',
    FILE_TRASHED: 'FILE_TRASHED',
    FILE_RECOVERED: 'FILE_RECOVERED',
    FILE_DELETED: 'FILE_DELETED',
    FILE_OPENED: 'FILE_OPENED',
    FILE_SHARED: 'FILE_SHARED',
    FILE_UNSHARED: 'FILE_UNSHARED'
});