angular.module('goboxWebapp')

.constant('SyncEventKind', {
    NEW_FILE: 'NEW_FILE',
    EDIT_FILE: 'EDIT_FILE',
    COPY_FILE: 'COPY_FILE',
    CUT_FILE: 'CUT_FILE',
    TRASH_FILE: 'TRASH_FILE',
    RECOVER_FILE: 'RECOVER_FILE',
    REMOVE_FILE: 'REMOVE_FILE',
    OPEN_FILE: 'OPEN_FILE',
    SHARE_FILE: 'SHARE_FILE',
    UNSHARE_FILE: 'UNSHARE_FILE'
});